### ISSUE TITLE
[79.13.468]No Such Method Error When open a barrel container.

### ISSUE THREAD

**Issue by innocentius** [Deadrik/TFCraft#735]
Description: Rendering screen

java.lang.NoSuchMethodError: com.bioxx.tfc.GUI.GuiBarrel.drawHoveringText(Ljava/util/List;IILnet/minecraft/client/gui/FontRenderer;)V
	at com.bioxx.tfc.GUI.GuiBarrel.drawTooltip(GuiBarrel.java:140)
	at com.bioxx.tfc.GUI.GuiBarrel$GuiBarrelTabButton.func_146112_a(GuiBarrel.java:237)
	at net.minecraft.client.gui.GuiScreen.func_73863_a(SourceFile:42)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:83)
	at com.bioxx.tfc.GUI.GuiContainerTFC.func_73863_a(GuiContainerTFC.java:44)
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1061)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:990)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by Kittychanley** [comment]
Please update to the latest commit and confirm that you can still reproduce the bug.
