### ISSUE TITLE
crash client

### ISSUE THREAD

**Issue by ArtBorax** [Deadrik/TFCraft#760]
java.lang.ArrayIndexOutOfBoundsException: 11
	at com.bioxx.tfc.Blocks.Flora.BlockFruitWood.func_149691_a(BlockFruitWood.java:58)
	at net.minecraft.block.Block.func_149673_e(Block.java:556)
	at net.minecraft.client.renderer.RenderBlocks.func_147793_a(RenderBlocks.java:8227)
	at net.minecraft.client.renderer.RenderBlocks.func_147808_b(RenderBlocks.java:5235)
	at net.minecraft.client.renderer.RenderBlocks.func_147784_q(RenderBlocks.java:4247)
	at com.bioxx.tfc.Render.TFC_CoreRender.RenderWoodTrunk(TFC_CoreRender.java:205)

**Comment by Kittychanley** [comment]
https://github.com/Deadrik/TFCraft/issues/582
