### ISSUE TITLE
crash client

### ISSUE THREAD

**Issue by ArtBorax** [Deadrik/TFCraft#761]
java.lang.NullPointerException: Unexpected error
	at com.bioxx.tfc.Render.TFC_CoreRender.RenderFruitLeaves(TFC_CoreRender.java:533)
	at com.bioxx.tfc.Handlers.Client.BlockRenderHandler.renderWorldBlock(BlockRenderHandler.java:83)
	at cpw.mods.fml.client.registry.RenderingRegistry.renderWorldBlock(RenderingRegistry.java:118)
	at net.minecraft.src.FMLRenderAccessLibrary.renderWorldBlock(FMLRenderAccessLibrary.java:53)
	at net.minecraft.client.renderer.RenderBlocks.func_147805_b(RenderBlocks.java:296)
	at net.minecraft.client.renderer.WorldRenderer.func_147892_a(WorldRenderer.java:181)
	at net.minecraft.client.renderer.RenderGlobal.func_72716_a(RenderGlobal.java:1530)

**Comment by Kittychanley** [comment]
https://github.com/Deadrik/TFCraft/issues/582
