### ISSUE TITLE
crash server

### ISSUE THREAD

**Issue by ArtBorax** [Deadrik/TFCraft#762]
java.lang.NoClassDefFoundError: net/minecraft/world/World$3
	at net.minecraft.world.World.func_147460_e(World.java:1090)
	at com.bioxx.tfc.Blocks.Flora.BlockLogNatural.notifyLeaves(BlockLogNatural.java:292)
	at com.bioxx.tfc.Blocks.Flora.BlockLogNatural.scanLogs(BlockLogNatural.java:277)
	at com.bioxx.tfc.Blocks.Flora.BlockLogNatural.scanLogs(BlockLogNatural.java:263)
	at com.bioxx.tfc.Blocks.Flora.BlockLogNatural.ProcessTree(BlockLogNatural.java:212)
	at com.bioxx.tfc.Blocks.Flora.BlockLogNatural.func_149636_a(BlockLogNatural.java:156)
	at com.bioxx.tfc.Blocks.Flora.BlockLogNatural.func_149681_a(BlockLogNatural.java:181)
	at net.minecraft.server.management.ItemInWorldManager.removeBlock(ItemInWorldManager.java:302)
	at net.minecraft.server.management.ItemInWorldManager.func_73084_b(ItemInWorldManager.java:358)
	at net.minecraft.server.management.ItemInWorldManager.func_73082_a(ItemInWorldManager.java:273)
	at net.minecraft.network.NetHandlerPlayServer.func_147345_a(NetHandlerPlayServer.java:769)
	at net.minecraft.network.play.client.C07PacketPlayerDigging.func_148833_a(SourceFile:53)
	at net.minecraft.network.play.client.C07PacketPlayerDigging.func_148833_a(SourceFile:8)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:244)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:173)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:980)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:423)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:798)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:658)
	at java.lang.Thread.run(Thread.java:722)

**Comment by Kittychanley** [comment]
https://github.com/Deadrik/TFCraft/issues/582
