### ISSUE TITLE
Worldgen creates vanilla doubletall plants with imvalid metadata

### ISSUE THREAD

**Issue by ProgrammerHero** [Deadrik/TFCraft#799]
The world will sometimes be decorated with vanilla 2 high plants, and some of these will have invalid metadata values.  In my tests I encountered a patch of flowers including sunflowers with metadata of 6 and 7 (2 high flowers don't go higher than 5).  When this flower patch loaded the game immediately crashed with rendering errors.

     java.lang.ArrayIndexOutOfBoundsException: 6
    	at net.minecraft.block.BlockDoublePlant.func_149888_a(BlockDoublePlant.java:128)
    	at net.minecraft.client.renderer.RenderBlocks.func_147774_a(RenderBlocks.java:3602)
    	at net.minecraft.client.renderer.RenderBlocks.func_147805_b(RenderBlocks.java:259)
    	at net.minecraft.client.renderer.WorldRenderer.func_147892_a(WorldRenderer.java:181)
    	at net.minecraft.client.renderer.RenderGlobal.func_72716_a(RenderGlobal.java:1553)
    	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1187)
    	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1015)
    	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001)
    	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
    	at net.minecraft.client.main.Main.main(SourceFile:148)
    	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    	at java.lang.reflect.Method.invoke(Method.java:483)
    	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

    == or ==

    java.lang.ArrayIndexOutOfBoundsException: 7
    	at net.minecraft.block.BlockDoublePlant.func_149888_a(BlockDoublePlant.java:128)
    	at net.minecraft.item.ItemDoublePlant.func_77617_a(SourceFile:19)
    	at net.minecraft.item.Item.func_77650_f(Item.java:440)
    	at net.minecraft.item.ItemStack.func_77954_c(ItemStack.java:117)
    	at net.minecraft.client.renderer.entity.RenderItem.renderItemIntoGUI(RenderItem.java:403)
    	at net.minecraft.client.renderer.entity.RenderItem.func_82406_b(RenderItem.java:565)
    	at net.minecraft.client.gui.GuiIngame.func_73832_a(GuiIngame.java:955)
    	at net.minecraftforge.client.GuiIngameForge.renderHotbar(GuiIngameForge.java:206)
    	at net.minecraftforge.client.GuiIngameForge.func_73830_a(GuiIngameForge.java:141)
    	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1038)
    	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001)
    	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
    	at net.minecraft.client.main.Main.main(SourceFile:148)
    	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    	at java.lang.reflect.Method.invoke(Method.java:483)
    	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

I'm not even sure these flowers are supposed to generate at all.  But it seems some of the vanilla biome decorators are still active.

While testing inside eclipse, I edited the BlockDoublePlant.func_149888_a function (which generates the index exception) and told it to just use an index of 0 instead of the block's value so I could get close the flowers and there were in fact 2 different types of sunflower (one having an invalid metadata of 7) including rose bushes and peonies (and possibly more - I forget).  And since the error was deferred and did not go through a TFC control path I was unable to discover its source.

I attempted to regenerate the world several times (TFCDefault/seed=6384441334007400601) but had inconsistent results (I seem to recall biome decoration is not tied to the seed), so [I have provided my test world where I discovered the error](http://www.programmerhero.com/files/TerraQuest.zip).  The offending flower can be found at coords 212,116,-11893 (inside a cave).  Teleporting or walking to those coordinates should cause one of the above errors to occur.

I realized I was testing with forge 1492 so I tried a couple extra versions: 1470, 1452, 1451, and the tfc recommended 1448 but the test world consistently crashed.  The only reason I can reason I can think of for this behaviour would be a worldgen/biome decoration change in forge between 1448 and 1492 but I didn't see one in the changelog.  Also preliminary testing with the released 0.79.22 version provided inconclusive with no flowers near that location.

**Comment by Kittychanley** [comment]
Just want to make sure I'm understanding this correctly. When using the released version, 0.79.22.761, the crash doesn't happen because there are no flowers being generated?

When you are using a development build though, it does happen? Which development build are you using exactly? What is the most recent commit in the build?

**Comment by ProgrammerHero** [comment]
Correct, 0.79.22.761 did not generate the flowers and did not crash, so if the error existed it didn't manifest.  And I was testing with development version 9e9a10c.  I ran the development build inside eclipse and outside with the same results.

**Comment by Kittychanley** [comment]
Now when you say "with the same results" you mean that you generated a brand new world with the specific seed and this new world also generated the flower that caused the crash, right? If you are doing nothing more than copying the world save over, the crash is going to continue to happen because the flower already exists.

**Comment by ProgrammerHero** [comment]
So I regenerated the world from only the seed 4 times now and it succeeded each time (no crash).  And then took the broken world and deleted the region data and regenerated it and it also worked (no crash).  In each case, no flowers spawned at all at the given location.  In a previous test, I deleted the region data and was able to reproduce the crash - I must have miscalculated the region that time.

There was also a nearby hotspring that changed shape each time so evidence the biome decorator is not based on seed.

**Comment by Kittychanley** [comment]
So I'm digging through the code, and it seems like this has to be a vanilla bug. The setting of the metadata for the flower is determined by a field that is never edited with TFC's code.

**Comment by ProgrammerHero** [comment]
Considering its a vanilla flower I believe it.  Is that biome decorator even supposed to activate for TFC?

**Comment by Kittychanley** [comment]
We don't ever explicitly call it, but that doesn't mean there will never be some fluke where the game thinks the biome is a vanilla one and tries to call it before it realized the biome is a TFC one.

**Comment by ProgrammerHero** [comment]
Ok, I'll delete them from my world for now and keep a copy of my broken save in case its useful sometime.  Hopefully the error doesn't come up again for me or anyone else (it seems very rare).

**Comment by Kittychanley** [comment]
Here's a link of it happening to somebody else without TFC installed:
http://www.minecraftforum.net/forums/support/modded-client-support/2516236-help-with-crash

And here's another one:
https://bugs.mojang.com/browse/MC-73593

So I'm going to go ahead and close this since it's not a TFC issue.

**Comment by ProgrammerHero** [comment]
The official bug report says the client is modded (bungeecord/craftbukkit) so something deeper might be happening.  I'm going to keep an eye on it for a while in case I can find something (maybe a forge bug? who knows).
